from dataclasses import dataclass
from typing import Dict, Optional, Sequence


@dataclass
class Zip2Addr:
    zipcode: str
    pref_kana: Optional[str] = None
    city_kana: Optional[str] = None
    town_kana: Optional[str] = None
    prefecture: Optional[str] = None
    city: Optional[str] = None
    town: Optional[str] = None
    multiple_postal: Optional[int] = None
    koaza: Optional[int] = None
    chome: Optional[int] = None
    multiple_town: Optional[int] = None
    update_status: Optional[int] = None
    change_reason: Optional[int] = None

    @classmethod
    def from_row(cls, row: Sequence) -> "Zip2Addr":
        # expects row in order as selected in api.py / generated by generate_db.py:
        # zipcode, jis_code, old_postal_code, pref_kana, city_kana, town_kana, prefecture, city, town, multiple_postal, koaza, chome, multiple_town, update_status, change_reason
        def _to_int(v):
            if v is None:
                return None
            try:
                s = str(v).strip()
                return int(s) if s != "" else None
            except Exception:
                return None

        return cls(
            zipcode=row[0],
            pref_kana=row[3] if len(row) > 3 else None,
            city_kana=row[4] if len(row) > 4 else None,
            town_kana=row[5] if len(row) > 5 else None,
            prefecture=row[6] if len(row) > 6 else None,
            city=row[7] if len(row) > 7 else None,
            town=row[8] if len(row) > 8 else None,
            multiple_postal=_to_int(row[9]) if len(row) > 9 else None,
            koaza=_to_int(row[10]) if len(row) > 10 else None,
            chome=_to_int(row[11]) if len(row) > 11 else None,
            multiple_town=_to_int(row[12]) if len(row) > 12 else None,
            update_status=_to_int(row[13]) if len(row) > 13 else None,
            change_reason=_to_int(row[14]) if len(row) > 14 else None,
        )

    def to_dict(self) -> Dict[str, Optional[str]]:
        return {
            "zipcode": self.zipcode,
            "pref_kana": self.pref_kana,
            "city_kana": self.city_kana,
            "town_kana": self.town_kana,
            "prefecture": self.prefecture,
            "city": self.city,
            "town": self.town,
            "multiple_postal": self.multiple_postal,
            "koaza": self.koaza,
            "chome": self.chome,
            "multiple_town": self.multiple_town,
            "update_status": self.update_status,
            "change_reason": self.change_reason,
        }
